### PR TITLE
Add link to Reactive Rabbit

### PR DESCRIPTION
**Pull request by mkiedys**
Reactive Rabbit is Reactive Streams driver for RabbitMQ/AMQP.

### CODE REVIEW

**Comment by viktorklang** [comment]
My sincere apologies for not seeing this until now (must investigate why I don't get notifications here).

We have just released 1.0.0.RC2 with updated spec and TCK which you'll want to dig into, hopefully the TCK should give more and better guidance than it did before.

**Comment by rkuhn** [comment]
Yes, indeed, I have no clue why I have not seen this earlier. Once #15 is merged this PR will likely not apply cleanly anymore, but then I could also just include it over there … done.

**Comment by mkiedys** [comment]
Every new release of TCK brings new useful test procedures. Thanks for that - this really helps to maintain compatibility with changing specification and catch new bugs.

I just upgraded to 1.0.0 RC3.

**Comment by mkiedys** [comment]
@viktorklang wrote:
> We have just released 1.0.0.RC2 with updated spec and TCK which you'll want to dig into, hopefully the TCK should give more and better guidance than it did before.

Every new release of TCK brings new useful test procedures. Thanks for that - this really helps to maintain compatibility with changing specification and catch new bugs.

I just upgraded to 1.0.0 RC3.

@rkuhn wrote:
> Yes, indeed, I have no clue why I have not seen this earlier. Once #15 is merged this PR will likely not apply cleanly anymore, but then I could also just include it over there … done.

Should I rebase against #15 ?

**Comment by viktorklang** [comment]
Hi,

1.0.0.RC4 should be out shortly,
I'd recommend waiting for that.

-- 
Cheers,
√

**Pull request closed without merging**
